service: mes-configuration-service

provider:
  name: aws
  runtime: nodejs8.10

package:
  individually: true

functions:
  get:
    handler: src/functions/get/framework/handler.handler
    events:
      - http:
          path: 'configuration/{scope}'
          method: get


plugins:
  - serverless-offline
